geotsint/urls.py
import os
from django.conf.urls import url
from django.contrib import admin
from main import views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'^login/', views.LoginView.as_view()),
    url(r'^logout/', views.LogoutView.as_view()),
    url(r'^register/', views.RegisterView.as_view()),
    url(r'^activate/(?P<id>\d+)/(?P<code>\w+)/', views.ActivateView.as_view()),
    
    url(r'^$', login_required(login_url='/login/')(views.MainView.as_view())),
    url(r'^select_product/', login_required(login_url='/login/')(views.SelectProductView.as_view())),
    url(r'^create_product/', login_required(login_url='/login/')(views.CreateProductView.as_view())),
    url(r'^create_futures/(?P<product_id>\d+)/', login_required(login_url='/login/')(views.CreateFuturesView.as_view())),
    url(r'^futures_view/(?P<id>\d+)/', login_required(login_url='/login/')(views.FuturesView.as_view())),
    url(r'^futures_view/', login_required(login_url='/login/')(views.FuturesListView.as_view())),
    url(r'^null/(?P<id>\d+)/', login_required(login_url='/login/')(views.NullView.as_view())),
    #url(r'^select_mirror/(?P<id>\d+)/(?P<mirror_id>\d+)/', login_required(login_url='/login/')(views.FuturesSelectMirrorView.as_view())),
    # url(r'^deal_view/(?P<id>\d+)/', login_required(login_url='/login/')(views.DealView.as_view())),
    # url(r'^submit/(?P<id>\d+)/', login_required(login_url='/login')(views.SubmitDealView.as_view())),
    url(r'^ok/(?P<id>\d+)/', login_required(login_url='/login')(views.OkDealView.as_view())),
    url(r'^cancel/(?P<id>\d+)/', login_required(login_url='/login')(views.CancelDealView.as_view())),
    url(r'^deal_view/', login_required(login_url='/login/')(views.DealListView.as_view())),
    url(r'^edit_contacts/', login_required(login_url='/login/')(views.EditContactsView.as_view())),
    url(r'^error/', views.ErrorView.as_view()),
    url(r'^about/', views.AboutView.as_view()),
    url(r'^current/', views.CurrentProductList.as_view()),
    
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
"""
urlpatterns = []
"""

main/models.py
from django.db import models
from django.contrib import auth
import string
import random
import decimal
import datetime


FUTURES_STATUSES = (
    ('free', 'free'),
    ('busy', 'busy'),
    ('done', 'done'),
    ('canc', 'canc'),
)
DEAL_STATUSES = (
    # ('void', 'void'), # Annullirovan
    ('wait', 'wait'),
    # ('busy', 'busy'),
    ('done', 'done'),
    ('canc', 'canc'),
)
ROUTES = (
    ('buy', 'покупка'),
    ('sell', 'продажа'),
)
USER_STATUSES = (
    ('', ''),
    ('created', 'created'),
    ('confirm', 'confirm'),
)

PRICE_MAX_DIGITS = 10
REPUTATION_MAX_DIGITS = 4
USER_STATUS_MAX_LENGTH = 7
EMAIL_CONFIRMATION_MAX_LENGTH = 20
REPUTATION_DIGITS = 5
WEEKDAYS = (
    'mon',
    'tue',
    'wed',
    'thu',
    'fri',
    'sat',
    'sun',
)

MIN_DEALS_AMOUNT = 10
MIRROR_LIMIT = 20


class User(models.Model):
    user = models.OneToOneField(auth.models.User)
    contacts = models.TextField()
    email_confirmation = models.CharField(max_length=EMAIL_CONFIRMATION_MAX_LENGTH)
    reputation = models.DecimalField(
        max_digits = REPUTATION_DIGITS+1,
        decimal_places = REPUTATION_DIGITS,
        default = '0.0',
    )
    status = models.CharField(
        default = '',
        max_length = USER_STATUS_MAX_LENGTH,
        choices = USER_STATUSES,
        null = True,
        blank = True
    )
    
    def gen_email_confirmation(self):
        choices = string.ascii_letters
        
        result = ''
        for i in range(EMAIL_CONFIRMATION_MAX_LENGTH):
            char = random.choice(choices)
            result += char
        
        self.email_confirmation = result
    
    def calculate_reputation(self):
        deals = Deal.objects.filter(
            models.Q(buyer_futures__goods__user=self)
            | models.Q(seller_futures__goods__user=self)
        ).filter(status__in=('done', 'canc'))
        if deals.count() > MIN_DEALS_AMOUNT:
            self.reputation = decimal.Decimal(
                deals.filter(status='done').count() / deals.count()
            )
        else:
            pass
    
    def save(self, *args, **kwargs):
        if not self.status and not self.email_confirmation:
            self.gen_email_confirmation()
        return super(User, self).save(*args, **kwargs)
    
    def __str__(self):
        return '{} {} {}'.format(self.user, self.reputation, self.status)

class LoginIP(models.Model):
    user = models.ForeignKey(User)
    ip = models.GenericIPAddressField()

class Product(models.Model):
    relevant = models.PositiveIntegerField(default=0) # For choose products
    name = models.CharField(max_length=1024)
    words = models.ManyToManyField('Word', blank=True) # Fill with creation
    property_name_list = models.ManyToManyField('PropertyName', blank=True)
    
    def save(self, *args, **kwargs):
        ret = super().save(*args, **kwargs)
        
        chunks = self.name.split()
        for chunk in chunks:
            if len(chunk) >= Word.MIN_LENGTH:
                word = Word.objects.get_or_create(val=chunk.lower())[0]
                self.words.add(word)
        
        return ret
    
    def __str__(self):
        return self.name

class Word(models.Model):
    val = models.CharField(max_length=50, unique=True)
    
    MIN_LENGTH = 3
    
    def __str__(self):
        return self.val

class PropertyName(models.Model):
    #id = models.AutoField()
    name = models.CharField(max_length=50)
    
    @classmethod
    def name_list(cls):
        lst = cls.objects.order_by('name').values('name')
        rst = [x['name'] for x in lst]
        return rst
    
    def __str__(self):
        return self.name

class Goods(models.Model):
    user = models.ForeignKey('User')
    product = models.ForeignKey('Product')
    property_list = models.ManyToManyField('Property')
    photo = models.URLField(null=True, blank=True)
    
    def __str__(self):
        return '{}'.format(self.product.name)

class Property(models.Model):
    name = models.ForeignKey('PropertyName')
    value = models.CharField(max_length=50)
    
    def __str__(self):
        return '{}: {}'.format(self.name.name, self.value)

class Futures(models.Model):
    goods = models.ForeignKey('Goods')
    price = models.DecimalField(max_digits=PRICE_MAX_DIGITS, decimal_places=0) # No decimal 
    route = models.CharField(max_length=4, choices=ROUTES)
    date_from = models.DateField()
    date_till = models.DateField()
    # Weekdays
    mon = models.BooleanField()
    tue = models.BooleanField()
    wed = models.BooleanField()
    thu = models.BooleanField()
    fri = models.BooleanField()
    sat = models.BooleanField()
    sun = models.BooleanField()
    # ...
    time_from = models.TimeField()
    time_till = models.TimeField()
    address = models.CharField(max_length=200)
    status = models.CharField(max_length=4, choices=FUTURES_STATUSES, default='free')
    
    @property
    def user(self):
        return self.goods.user
    
    @property
    def reputation(self):
        return self.user.reputation
    
    @property
    def weekdays(self):
        if hasattr(self, '_mirror_futures'):
            return '{}{}{}{}{}{}{}'.format(
                int(self.mon) and int(self._mirror_futures.mon),
                int(self.tue) and int(self._mirror_futures.tue),
                int(self.wed) and int(self._mirror_futures.wed),
                int(self.thu) and int(self._mirror_futures.thu),
                int(self.fri) and int(self._mirror_futures.fri),
                int(self.sat) and int(self._mirror_futures.sat),
                int(self.sun) and int(self._mirror_futures.sun),
            )
        else:
            return '{}{}{}{}{}{}{}'.format(
                int(self.mon),
                int(self.tue),
                int(self.wed),
                int(self.thu),
                int(self.fri),
                int(self.sat),
                int(self.sun),
            )
    
    def get_route(self):
        for en, ru in ROUTES:
            if en == self.route:
                return ru
    
    def mirror_futures(self):
        route = 'buy' if self.route == 'sell' else 'sell'
        q = models.Q(address=self.address) | models.Q(address__startswith=self.address)
        res = ''
        for st in self.address.split(', '):
            if res:
                res += ', '.join((res, st))
            else:
                res = st
            q = q | models.Q(address=res)
        queryset = Futures.objects.filter(
            models.Q(
                # Address
                q
                
                # Date
                & ~models.Q(
                    models.Q(
                        date_till__lt = self.date_from
                    )
                    | models.Q(
                        date_from__gt = self.date_till
                    )
                )
                
                # Weekdays
                & models.Q(
                    models.Q(
                        models.Q(
                            mon = self.mon
                        )
                        & models.Q(
                            mon = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            tue = self.tue
                        )
                        & models.Q(
                            tue = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            wed = self.wed
                        )
                        & models.Q(
                            wed = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            thu = self.thu
                        )
                        & models.Q(
                            thu = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            fri = self.fri
                        )
                        & models.Q(
                            fri = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            sat = self.sat
                        )
                        & models.Q(
                            sat = True
                        )
                    )
                    | models.Q(
                        models.Q(
                            sun = self.sun
                        )
                        & models.Q(
                            sun = True
                        )
                    )
                )
                
                # Time
                & models.Q(
                    models.Q( # time_from in (time_from, time_till)
                        models.Q(time_from__gte=self.time_from)
                        & models.Q(time_from__lte=self.time_till)
                    )
                    | models.Q( # time_till in (fime_from, time_till)
                        models.Q(time_till__gte=self.time_from)
                        & models.Q(time_till__lte=self.time_till)
                    )
                    | models.Q( # time_from, time_till contains (time_from, time_till)
                        models.Q(time_from__lt=self.time_from)
                        & models.Q(time_till__gt=self.time_till)
                    )
                ),
            ),
            route = route,
            goods__product = self.goods.product,
            status = 'free',
            goods__user__reputation__lte = self.reputation,
        ).exclude(goods__user__id = self.goods.user_id)
        
        queryset = queryset.order_by('-goods__user__reputation',  'price')
        queryset = queryset[:MIRROR_LIMIT]
        L = []
        for q in queryset:
            q._mirror_futures = self
            L.append(q)
        
        return L
    

main/forms.py
from django import forms
import django.forms
from django.contrib import auth
from . import models
import datetime

class LoginForm(forms.Form):
    login = forms.CharField(label='Логин', max_length=100)
    password = forms.CharField(label='Пароль', max_length=100, widget=forms.PasswordInput)
    
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        
        login = cleaned_data.get('login')
        password = cleaned_data.get('password')
        
        user = auth.authenticate(username=login, password=password)
        if user is None:
            raise django.forms.ValidationError("Неверные логин/пароль")
        if not user.is_active:
            raise django.forms.ValidationError("Пользователь заблокирован")
        
        self.user = user
        
        return cleaned_data


class RegisterForm(forms.Form):
    login = forms.CharField(label='Ник', max_length=100)
    password = forms.CharField(label='Пароль', max_length=100, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Пароль еще раз', max_length=100, widget=forms.PasswordInput)
    contacts = forms.CharField(label='Контакты', widget=forms.Textarea)
    email = forms.EmailField(label='Почта')
    
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        
        if auth.models.User.objects.filter(
            username=cleaned_data.get('login')
        ).exists():
            raise django.forms.ValidationError("Логин уже существует")
        if auth.models.User.objects.filter(
            email=cleaned_data.get('email')
        ).exists():
            raise django.forms.ValidationError("E-mail уже существует")
        if cleaned_data.get('password') != cleaned_data.get('password_confirm'):
            raise django.forms.ValidationError('Пароли не совпадают')
        
        return cleaned_data


class SelectProductForm(forms.Form):
    words = forms.CharField(label='Слова для поиска', max_length=200, required=False)


class CreateProductForm(forms.Form):
    name = forms.CharField(label='Называние', max_length=1024, widget=forms.Textarea)
    property_name_list = forms.MultipleChoiceField(
        label = 'Названия свойств',
        widget = forms.CheckboxSelectMultiple,
        choices = zip(
            models.PropertyName.name_list(),
            models.PropertyName.name_list()
        ))


class CreateFuturesForm(forms.Form):
    price = forms.DecimalField(label='Цена', max_digits=models.PRICE_MAX_DIGITS)
    date_from = forms.CharField(label='Дата от')
    date_till = forms.CharField(label='Дата до', required=False)
    time_from = forms.TimeField(label='Время от', initial='00:00')
    time_till = forms.TimeField(label='Время до', initial='23:59')
    mon = forms.BooleanField(label='Пн', initial=True, required=False)
    tue = forms.BooleanField(label='Вт', initial=True, required=False)
    wed = forms.BooleanField(label='Ср', initial=True, required=False)
    thu = forms.BooleanField(label='Чт', initial=True, required=False)
    fri = forms.BooleanField(label='Пт', initial=True, required=False)
    sat = forms.BooleanField(label='Сб', initial=True, required=False)
    sun = forms.BooleanField(label='Вс', initial=True, required=False)
    address = forms.CharField(label='Место', max_length=300, help_text='введите адрес, разделяя позиции запятой')
    route = forms.ChoiceField(label='Направление', choices=models.ROUTES, widget=forms.RadioSelect)
    
    def __init__(self, *args, property_name_list, **kwargs):
        # Add property fields
        for property_name in property_name_list:
            self.base_fields[property_name[0]] = forms.CharField(label=property_name[1])
        
        ret = super(CreateFuturesForm, self).__init__(*args, **kwargs)
        
        self.fields['address'].widget.attrs['style'] = 'width:600px;'
    
    def clean_date_from(self):
        str = self.cleaned_data['date_from']
        return datetime.datetime.strptime(str, '%d.%m.%Y').date()
    
    def clean_date_till(self):
        str = self.cleaned_data['date_till']
        if str:
            return datetime.datetime.strptime(str, '%d.%m.%Y').date()
        # raise forms.ValidationError('Введите дату')
    
    def clean(self):
        data = super(CreateFuturesForm, self).clean()
        
        # try:
            # time_from = datetime.datetime.strptime(data['time_from'], '%H:%M')
            # if data['time_till']:
                # time_till = datetime.datetime.strptime(data['time_till'], '%H:%M')
            # else:
                # time_till = None
        # except Exception as err:
            # raise django.forms.ValidationError('{} {}'.format(data['time_from'], data['time_till']))
        
        return data


class EditContactsForm(forms.Form):
    contacts = forms.CharField(label='Контакты', widget=forms.Textarea)

main/templates/about.html
{% extends "base_page.html"%}

{% block "content"%}
    <h1>О сайте geotsint.ru</h1>
    
    <h2>ГЕОЦИНТ</h2>
    <p>
Система для покупки и продажи вещей, товаров, продуктов.<p> Основана на кибер-сетевой структуре.
<h3>Принцип</h3>
<p>Вы создаете фьючерс (товар с обязательством его продажи/покупки), потом выбираете ему соответствующий фьючерс с обратным направлением продажи/покупки. Этим вы создаете сделку между двумя пользователями и получаете доступ к контактной информации партнера. Далее Вы либо подтверждаете факт выполнения сделки, либо отрицаете данный факт. Если хотя бы одна сторона орицает, то сделка считается несостоявшейся, что негативно отразится на рейтингах обеих сторон.
<hr/>
<p>Выбрать антифьючерс пользователь может только меньшего рейтинга, чем он сам.
<ul>Рейтинги фьючерса определяются динамически по принципам:</ul>
<li>Другие сделки пользователя</li>
<li>Регион (город)</li>
<li>Законченный фьючерс может быть только 2 видов: "done" и "canc". Соответственно "1" и "0". Поэтому рейтинги незаконченных фьючерсов располагаются в диапозоне 0-1 и являются вещественным числом. Рейтинг фьючерса должен исходить из того принципа, чтобы статистически постараться предсказать исход сделки и обозначить погрешность, которая может вытекать из малого количества сделок у субъекта.</li>
<li>Рейтинги бывших партнеров, а также собственная и их диверсифицированность.</li>
</ul>
<h3>Типичные персонажи</h3>
<p><strong>Бабушка в поселке</strong>. Бабушка живет на окраине небольшого поселка, держит козу. Ей самой молока много,
она ходит каждое утро с парным молоком на минирынок, стоит там весь день, продает. Зачем? Она может создать фьючерсы на
месяц (каждый день, "молоко парное", с 9 до 10-ти часов, адрес такой-то) и тогда у нее купят это молоко все желающие и
ходить никуда ей не придется.
<p><strong>Таджик</strong>. Таджик прилетел работать, взял с собой пару кг. спелых персиков (гораздо вкуснее, чем в
магазине!). Он создал фьючерс перед вылетом (один раз, "персики спелые", с 12 до 13 часов такого-то числа, адрес -
аэропорт такой-то). Мелоч, но ему небольшие деньги и человеку, который купит хорошо. Главное смотреть на рейтинг человека,
чтобы не было обмана.
<p><strong>Человек</strong>. Любит домашнее и натуральное, поэтому создает фьючерсы (завтра, в любое время, в моем городе, куплю,
"парное молоко", "спелые персики").
<p><strong>:)</strong>
{% endblock %}

main/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>Геоцинт. Покупай и продавай фьючерсы!</title>
        
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script>
            /* Russian (UTF-8) initialisation for the jQuery UI date picker plugin. */
            /* Written by Andrew Stromnov (stromnov@gmail.com). */
            ( function( factory ) {
                if ( typeof define === "function" && define.amd ) {

                    // AMD. Register as an anonymous module.
                    define( [ "../widgets/datepicker" ], factory );
                } else {

                    // Browser globals
                    factory( jQuery.datepicker );
                }
            }( function( datepicker ) {

            datepicker.regional.ru = {
                closeText: "Закрыть",
                prevText: "&#x3C;Пред",
                nextText: "След&#x3E;",
                currentText: "Сегодня",
                monthNames: [ "Январь","Февраль","Март","Апрель","Май","Июнь",
                "Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь" ],
                monthNamesShort: [ "Янв","Фев","Мар","Апр","Май","Июн",
                "Июл","Авг","Сен","Окт","Ноя","Дек" ],
                dayNames: [ "воскресенье","понедельник","вторник","среда","четверг","пятница","суббота" ],
                dayNamesShort: [ "вск","пнд","втр","срд","чтв","птн","сбт" ],
                dayNamesMin: [ "Вс","Пн","Вт","Ср","Чт","Пт","Сб" ],
                weekHeader: "Нед",
                dateFormat: "dd.mm.yy",
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: "" };
            datepicker.setDefaults( datepicker.regional.ru );

            return datepicker.regional.ru;

            } ) );
        </script>
        
        <link href="/static/js/kladrapi-jsclient/jquery.kladr.min.css" rel="stylesheet">
        <link href="/static/js/jquery-timepicker/jquery.timepicker.css" rel="stylesheet">
        <link href="/static/js/kladrapi-jsclient/examples/css/all.css" rel="stylesheet">

        <script src="/static/js/kladrapi-jsclient/jquery.kladr.min.js" type="text/javascript"></script>
        <script src="/static/js/jquery-timepicker/jquery.timepicker.min.js" type="text/javascript"></script>
        
        <script>
            $.datepicker.formatDate( "dd.mm.yy", new Date( 2007, 7 - 1, 14 ), {
              dayNamesShort: $.datepicker.regional[ "ru" ].dayNamesShort,
              dayNames: $.datepicker.regional[ "ru" ].dayNames,
              monthNamesShort: $.datepicker.regional[ "ru" ].monthNamesShort,
              monthNames: $.datepicker.regional[ "ru" ].monthNames
            });
        </script>
        
        <style>
        .red_class {
            //color: "red"; /* Цвет символа */
            font-size: 150%; /* Размер шрифта */
        } 
        </style>
        
        {% block "extrahead" %}
        {% endblock %}
    </head>
    
    <body>
        <div>
            {% if user.username %}
                Вы вошли как "{{ user.username }}".
            {% else %}
                Вы не аутентифицированны, <a href="/login/">аутентифицируйтесь здесь</a>.
            {% endif %}
        </div>
        
        {% block "main"%}
        {% endblock %}
        
        <footer>
            <p><em>Сайт создан by Dmitriy Shikhalev &lt;dmitriy.shikhalev@gmail.com&gt</em>
            <p><em><a href="https://dmitriy_shikhalev@bitbucket.org/dmitriy_shikhalev/geotsint.git">Исходный код</a></em>
        </footer>
    </body>
</html>

main/templates/base_page.html
{% extends "base.html"%}

{% block "main"%}
    <div>
        <a href="/">Перейти в начало</a>
    </div>
    
    {% block "content"%}
    {% endblock %}
{% endblock %}

main/templates/create_futures.html
{% extends "base_page.html"%}

{% block "extrahead" %}
    <script>
        $(function() {
            $("[name='address']").kladr({
                oneString: true
            });
        });
    </script>
    
    <script>
        $(function() {
            $("[name='date_from']").datepicker();
            $("[name='date_till']").datepicker();
            $("[name='time_from']").timepicker({ 'scrollDefault': 'now', 'step': 15, 'timeFormat': 'H:i'});
            $("[name='time_till']").timepicker({ 'scrollDefault': 'now', 'step': 15, 'timeFormat': 'H:i'});
        });
    </script>
{% endblock %}

{% block "content"%}
    <table border="1">
        <tr>
            <th colspan="2">
                <h1>Создание фьючерса на продукт "{{ product.name }}"</h1>
            </th>
        </tr>
        
        <form url='/create_futures' method='POST'> {% csrf_token %}
            {{ form.as_table }}
            <!-- <input name="address" type="text" value="" placeholder="Адрес"> -->
            
            <tr>
                <td colspan="2">
                    <input type="submit" value="Создать" />
                </td>
            </tr>
        </form>
    </table>
{% endblock %}

main/templates/create_product.html
{% extends "base_page.html"%}

{% block "content"%}
    <table>
        <tr>
            <th>
                <h1>Создание продукта</h1>
            </th>
        </tr>
        
        <form url='/create_product' method='POST'>
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td>
                    <input type="submit" value="Создать" />
                </td>
            </tr>
        </form>
    </table>
{% endblock %}

main/templates/current_product_list.html
{% extends "base_page.html"%}

{% block "content"%}
	<h1>Список текущих продуктов, ожидающих сделки</h1>
	
	<table border="1">
		<tr>
			<th>Покупка</th>
		</tr>
		{% for product in products_buy %}
			<tr>
				<td>{{ product.name }}</td>
			</tr>
		{% empty %}
			<tr>
				<td><em>Ничего нет для покупки</em></td>
			</tr>
		{% endfor %}
		<tr>
			<th>Продажа</th>
		</tr>
		{% for product in products_sell %}
			<tr>
				<td>{{ product.name }}</td>
			</tr>
		{% empty %}
			<tr>
				<td><em>Ничего нет для продажи</em></td>
			</tr>
		{% endfor %}
	</table>
{% endblock %}

main/templates/deal_list_view.html
{% extends "base_page.html"%}

{% block "content"%}
    <table border="1">
        <tr>
            <th colspan="11">
                <h1>Список текущих сделок</h1>
            </th>
        </tr>
        
        <tr>
            <td colspan="11"><em>Свои контакты</em>: <strong>{{ user.user.contacts }}</strong></td>
        </tr>
        
        <tr>
            <th>Название продукта покупки</th>
            <th>Название продукта продажи</th>
            <th>Цена</th>
            <th>Дата от</th>
            <th>Дата до</th>
            <th>Время от</th>
            <th>Время до</th>
            <th>Дни недели</th>
            <th>Место</th>
            <th>Контакты партнера</th>
        </tr>
        {% for deal in deals %}
            <tr>
                <td>{{ deal.buyer_futures.goods.product.name }}</td>
                <td>{{ deal.seller_futures.goods.product.name }}</td>
                <td>{{ deal.price }}</td>
                <td>{{ deal.date_from }}</td>
                <td>{{ deal.date_till }}</td>
                <td>{{ deal.time_from }}</td>
                <td>{{ deal.time_till }}</td>
                <td>{{ deal.weekdays }}</td>
                <td>{{ deal.address }}</td>
                <td>{{ deal.partner.contacts }}</td>
                <td><a href='/ok/{{ deal.id }}/'>Подтвердить сделку</a>
                <td><a href='/cancel/{{ deal.id }}/'>Отменить сделку</a>
            </tr>
        {% empty %}
            <tr>
                <td colspan="11">Незавершенных сделок нет</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

main/templates/edit_contacts_view.html
{% extends "base_page.html"%}

{% block "content"%}
    <table border="1">
        <tr>
            <th colspan="2">
                <h1>Изменить свои контакты</h1>
            </th>
        </tr>
        
        <form url='/edit_contacts/' method='POST'> {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td colspan="2">
                    <input type="submit" value="Изменить" />
                </td>
            </tr>
        </form>
    </table>
{% endblock %}

main/templates/error.html
{% extends "base_page.html"%}

{% block "content"%}
    <h1>Ошибка!</h1>
    <div>
        {{ error }}
    </div>
{% endblock %}

main/templates/futures_list_view.html
{% extends "base_page.html"%}

{% block "content"%}
    <table border="1">
        <tr>
            <th colspan="7">
                <h1>Список фьючерсов</h1>
            </th>
        </tr>
        <tr>
            <th>Название продукта</th>
            <th>Направление</th>
            <th>Дата от</th>
            <th>Дата до</th>
            <th>Время от</th>
            <th>Время до</th>
            <th>Дни недели</th>
        </tr>
        
        {% for futures in futures_list %}
            <tr>
                <td><a href='/futures_view/{{ futures.id }}/'>{{ futures.goods.product.name }}</a></td>
                <td>{{ futures.get_route }}</td>
                <td>{{ futures.date_from }}</td>
                <td>{{ futures.date_till }}</td>
                <td>{{ futures.time_from }}</td>
                <td>{{ futures.time_till }}</td>
                <td>{{ futures.weekdays }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

main/templates/register.html
{% extends "base.html"%}

{% block "main"%}
    <table>
        <tr>
            <th>
                <h1>Регистрация</h1>
            </th>
        </tr>
            
        <form url='/register' method='POST'> {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td>
                    <input type="submit" value="Зарегистрироваться" />
                </td>
            </tr>
        </form>
    </table>
{% endblock %}